import React from 'react';
import './flatly.css';
import './flatty-add-on.css';


class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {a: "a", b: "b", c: "c", message: "", as: "a", bs: "b", cs: "c", smessage: ""}
  }

  handleGetHelloClient = () => {
    this.setState({message: "Hello world generated by client"})
  }
  handleGetHelloServer = () => {
    fetch("/.netlify/functions/hello")
        .then(res => res.json())
        .then(data => this.setState({smessage: data.message}))
  }
  handleChange = (e) => {
    this.setState({[e.target.name]: e.target.value})
  }

  handleAddClient = (a, b) => {
    const c = parseInt(a) + parseInt(b)
    this.setState({c})
  }

  handleAddServer = (a, b) => {
    const data = {
      a: a,
      b: b
    }
    const options = {
      method: 'POST',
      body: JSON.stringify(data),
      headers: {
        'Content-Type': 'application/json'
      }
    }
    fetch("/.netlify/functions/add", options)
        .then(res => res.json())
        .then(data => {
          const {a, b} = data
          const c = parseInt(a) + parseInt(b)
          this.setState({c})
        }).catch(err => alert(err))

  }

  render() {
    const {a, b, c, message} = this.state
    const {as, bs, cs, smessage} = this.state
    return (
        <div>
          <div>
            <div className="container">
              <section>
                <div className="card border-primary mb-3">
                  <div className="card-header">
                    <span>Generate "Hello-world" client side</span>
                  </div>
                  <div className="card-body">
                    <h4 className="card-title"/>
                    <div className="form-group">
                      <div className='flex-center'>
                        <button type="button" className="btn btn-primary btn-lg"
                                onClick={() => {
                                  this.handleGetHelloClient(a, b)
                                }}>Submit
                        </button>
                        <button type="button" className="btn btn-primary btn-lg"
                                onClick={() => {
                                  this.setState({message: ""})
                                }}>Clear
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="card-header">
                    <span>Output: </span>
                    <span>{message}</span>
                  </div>
                </div>
                <div className="card border-primary mb-3">
                  <div className="card-header">
                    <span>Generate "Hello-world" server side</span>
                  </div>
                  <div className="card-body">
                    <h4 className="card-title"/>
                    <div className="form-group">
                      <div className='flex-center'>
                        <button type="button" className="btn btn-primary btn-lg"
                                onClick={() => {
                                  this.handleGetHelloServer(a, b)
                                }}>Submit
                        </button>
                        <button type="button" className="btn btn-primary btn-lg"
                                onClick={() => {
                                  this.setState({smessage: ""})
                                }}>Clear
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="card-header">
                    <span>Output: </span>
                    <span>{smessage}</span>
                  </div>
                </div>
              </section>
            </div>
          </div>

          <div style={{backgroundColor: "#ecf0f1", marginBottom: "100px"}}>
            <div className="container">
              <section>
                <div className="card border-primary mb-3">
                  <div className="card-header">
                    <span>Add a and b client side</span>
                  </div>
                  <div className="card-body">
                    <h4 className="card-title"> a + b</h4>
                    <div className="form-group">
                      <input className="form-control form-control-lg" type="text" placeholder="a"
                             id="inputLarge" value={a} name="a"
                             onChange={(e) => this.handleChange(e)}/>
                      <input className="form-control form-control-lg" type="text" placeholder="b"
                             id="inputLarge" value={b} name="b"
                             onChange={(e) => this.handleChange(e)}/>
                      <div style={{textAlign: "center"}}>
                        <button type="button" className="btn btn-primary btn-lg"
                                onClick={() => {
                                  this.handleAddClient(a, b)
                                }}>Add
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="card-header">
                    <span>Output: </span>
                    <span>{c}</span>
                  </div>
                </div>
                <div className="card border-primary mb-3">
                  <div className="card-header">
                    <span>Add a and b server side</span>
                  </div>
                  <div className="card-body">
                    <h4 className="card-title"> a + b</h4>
                    <div className="form-group">
                      <input className="form-control form-control-lg" type="text" placeholder="a"
                             id="inputLarge" value={as} name="as"
                             onChange={(e) => this.handleChange(e)}/>
                      <input className="form-control form-control-lg" type="text" placeholder="b"
                             id="inputLarge" value={bs} name="bs"
                             onChange={(e) => this.handleChange(e)}/>
                      <div style={{textAlign: "center"}}>
                        <button type="button" className="btn btn-primary btn-lg"
                                onClick={() => {
                                  this.handleAddServer(as, bs)
                                }}>Add
                        </button>
                      </div>
                    </div>
                  </div>
                  <div className="card-header">
                    <span>Output: </span>
                    <span>{cs}</span>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </div>


    );
  }
}

export default App;
